# Generated by Django 4.0.3 on 2022-03-17 09:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allprojects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='/static/image/node.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
