# Generated by Django 3.2.7 on 2022-03-22 13:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allprojects', '0007_auto_20220322_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.png', max_length=255, verbose_name='image'),
        ),
    ]
